version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./logs:/app/logs
      - ./dbt_project:/app/dbt_project # Mount dbt project for access within container
    command: bash -c "python scripts/load_to_postgres.py && dbt debug --project-dir /app/dbt_project && dbt seed --project-dir /app/dbt_project && dbt run --project-dir /app/dbt_project && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: