version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./data/raw/telegram_messages:/app/data/raw/telegram_messages
      - ./data/raw/telegram_images:/app/data/raw/telegram_images
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_PHONE_NUMBER: ${TELEGRAM_PHONE_NUMBER}
      RAW_DATA_DIR: ${RAW_DATA_DIR}
      RAW_IMAGES_DIR: ${RAW_IMAGES_DIR}
      LOG_DIR: ${LOG_DIR}
    command: python ./scripts/scrape_telegram.py
    # >>> THESE LINES ARE ADDED/UNCOMMENTED FOR INTERACTIVE AUTHENTICATION <<<
    stdin_open: true # Keeps stdin open for interactive input
    tty: true        # Allocates a pseudo-TTY for interactive input

volumes:
  postgres_data: